name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Download submodules
        run: |
          git submodule update --init --recursive
      - name: Install cibuildwheel
        run: |
          python -m pip install -r requirements.txt
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_BEFORE_BUILD: pip install -r requirements.txt
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
