name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - uses: seanmiddleditch/gha-setup-ninja@master
        name: Install Ninja

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Build wheels
        run: |
          python setup.py clean
          python setup.py build --build-type RelWithDebInfo -G Ninja
        env:
          CIBW_BUILD: "cp37-*"
          CIBW_BEFORE_BUILD:

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
